swagger: '2.0'
info:
  version: '0.3.1'
  title: User Management
  description: User Management API

basePath: /usermanagement/
schemes:
  - http
  - https

produces:
  - application/json

paths:
  /usermanagement/users:
    get:
      description: Returns all users
      operationId: getUsers
      produces:
        - application/json
      responses:
        '200':
          description: user response
          schema:
            $ref: '#/definitions/GetUsersReply'

definitions:
  User:
    id: User
    type: object
    properties:
      userName:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      age:
        type: integer
        format: int64
      emailAddress:
        type: string
  GetUsersReply:
    id: GetUsersReply
    type: object
    properties:
      users:
        type: array
        items:
          $ref: '#/definitions/User'

